;(function($,window,document,undefined){(function(){var lastTime=0;var vendors=['ms','moz','webkit','o'];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+'RequestAnimationFrame'];window.cancelAnimationFrame=window[vendors[x]+'CancelAnimationFrame']||window[vendors[x]+'CancelRequestAnimationFrame'];}
if(!window.requestAnimationFrame)
window.requestAnimationFrame=function(callback){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};if(!window.cancelAnimationFrame)
window.cancelAnimationFrame=function(id){clearTimeout(id);};}());function Parallax(element,options){var self=this;this.boxWidthComp=0;if(typeof options=='object'){delete options.refresh;delete options.render;$.extend(this,options);}
this.$element=$(element);if(!this.imageSrc&&this.$element.is('img')){this.imageSrc=this.$element.attr('src');}
this.positionX=this.position[0];this.positionY=this.position[1];if($.isMobile()&&this.cover===false){this.$element.css({backgroundImage:'url('+this.imageSrc+')',backgroundPosition:this.touchPosition});return this;}
this.$mirror=$('<div />').prependTo('body');this.$slider=$('<img />').hide().prependTo(this.$mirror);if(this.imageAlt)this.$slider.attr('alt',this.imageAlt);this.$mirror.addClass('parallax-mirror').css({visibility:'hidden',zIndex:this.zIndex,position:'fixed',top:0,left:0,overflow:'hidden',opacity:this.bgOpacity});this.$slider.addClass('parallax-slider').one('load',function(){if(!self.naturalHeight||!self.naturalWidth){self.naturalHeight=this.naturalHeight||this.height||1;self.naturalWidth=this.naturalWidth||this.width||1;}
self.aspectRatio=self.naturalWidth/self.naturalHeight;Parallax.isSetup||Parallax.setup();Parallax.sliders.push(self);Parallax.isFresh=false;Parallax.requestRender();});this.$slider[0].src=this.imageSrc;if(this.$slider[0].complete){this.$slider.fadeIn('slow');}
else{this.$slider.on("load",function(){$(this).fadeIn('slow');});}
if(this.naturalHeight&&this.naturalWidth||this.$slider[0].complete){this.$slider.trigger('load');}};$.extend(Parallax.prototype,{speed:0.2,bleed:0,zIndex:-100,position:['center','center'],touchPosition:'center center',bgOpacity:1,overScrollFix:false,cover:false,refresh:function(){this.boxWidth=this.$element.outerWidth();if(this.cover===true){this.boxHeight=$(document).height()+this.bleed*2;this.boxWidth=$(window).width();}else{this.boxHeight=this.$element.outerHeight()+this.bleed*2;this.boxWidth=this.$element.outerWidth();}
this.boxOffsetTop=this.$element.offset().top-this.bleed;this.boxOffsetLeft=this.$element.offset().left;this.boxOffsetBottom=this.boxOffsetTop+this.boxHeight;var winHeight=Parallax.winHeight;var docHeight=Parallax.docHeight;var maxOffset=Math.min(this.boxOffsetTop,docHeight-winHeight);var minOffset=Math.max(this.boxOffsetTop+this.boxHeight-winHeight,0);var imageHeightMin=this.boxHeight+(maxOffset-minOffset)*(1-this.speed)|0;var imageOffsetMin=(this.boxOffsetTop-maxOffset)*(1-this.speed)|0;if(imageHeightMin*this.aspectRatio>=this.boxWidth){this.imageWidth=imageHeightMin*this.aspectRatio|0;this.imageHeight=imageHeightMin;this.offsetBaseTop=imageOffsetMin;var margin=this.imageWidth-this.boxWidth;this.boxWidthComp=margin;if(this.positionX=='left'){this.offsetLeft=0;}else if(this.positionX=='right'){this.offsetLeft=-margin;}else{this.offsetLeft=-margin/2|0;}}else{this.imageWidth=this.boxWidth;this.imageHeight=this.boxWidth/this.aspectRatio|0;this.offsetLeft=0;var margin=this.imageHeight-imageHeightMin;if(this.positionY=='top'){this.offsetBaseTop=imageOffsetMin;}else if(this.positionY=='bottom'){this.offsetBaseTop=imageOffsetMin-margin;}else{this.offsetBaseTop=imageOffsetMin-margin/2|0;}}},render:function(){var scrollTop=Parallax.scrollTop;var scrollLeft=Parallax.scrollLeft;var overScroll=this.overScrollFix?Parallax.overScroll:0;var scrollBottom=scrollTop+Parallax.winHeight;if(this.boxOffsetBottom>scrollTop&&this.boxOffsetTop<scrollBottom){this.visibility='visible';this.mirrorTop=this.boxOffsetTop-scrollTop;this.mirrorLeft=this.boxOffsetLeft-scrollLeft;this.offsetTop=this.offsetBaseTop-this.mirrorTop*(1-this.speed);}else{this.visibility='hidden';}
this.$mirror.css({transform:'translate3d(0px, 0px, 0px)',visibility:this.visibility,top:Math.round(this.mirrorTop-overScroll),left:this.mirrorLeft,height:this.boxHeight,width:this.boxWidth+this.boxWidthComp});var transl='translate3d( 0px,'+Math.round(this.offsetTop)+'px, 0px)';this.$slider.css({position:'absolute',top:0,transform:transl,left:this.offsetLeft,height:this.imageHeight,width:this.imageWidth});}});$.extend(Parallax,{scrollTop:0,scrollLeft:0,winHeight:0,winWidth:0,docHeight:1<<30,docWidth:1<<30,sliders:[],isReady:false,isFresh:false,isBusy:false,lastTop:1,setup:function(){if(this.isReady)return;var $doc=$(document),$win=$(window);if($.isMobile()){Parallax.winHeight=$win.height();Parallax.winWidth=$win.width();Parallax.docHeight=$doc.height();Parallax.docWidth=$doc.width();Parallax.isFresh=false;Parallax.requestRender();}
else{$win.on('scroll.px.parallax load.px.parallax',function(){var scrollTopMax=Parallax.docHeight-Parallax.winHeight;var scrollLeftMax=Parallax.docWidth-Parallax.winWidth;Parallax.scrollTop=Math.max(0,Math.min(scrollTopMax,$win.scrollTop()));Parallax.scrollLeft=Math.max(0,Math.min(scrollLeftMax,$win.scrollLeft()));Parallax.overScroll=Math.max($win.scrollTop()-scrollTopMax,Math.min($win.scrollTop(),0));Parallax.requestRender();}).on('resize.px.parallax load.px.parallax',function(){Parallax.winHeight=$win.height();Parallax.winWidth=$win.width();Parallax.docHeight=$doc.height();Parallax.docWidth=$doc.width();Parallax.isFresh=false;Parallax.requestRender();});}
this.isReady=true;},configure:function(options){if(typeof options=='object'){delete options.refresh;delete options.render;$.extend(this.prototype,options);}},refresh:function(){$.each(this.sliders,function(){this.refresh()});this.isFresh=true;},render:function(){this.isFresh||this.refresh();$.each(this.sliders,function(){this.render()});},requestRender:function(){var self=this;if(!this.isBusy){this.isBusy=true;self.render();self.isBusy=false;}}});function Plugin(option){return this.each(function(){var $this=$(this);var options=typeof option=='object'&&option;if(this==window||this==document||$this.is('body')){Parallax.configure(options);}
else if(!$this.data('px.parallax')){options=$.extend({},$this.data(),options);$this.data('px.parallax',new Parallax(this,options));}
if(typeof option=='string'){Parallax[option]();}})};var old=$.fn.parallax;$.fn.parallax=Plugin;$.fn.parallax.Constructor=Parallax;$.fn.parallax.noConflict=function(){$.fn.parallax=old;return this;};$(document).on('ready.px.parallax.data-api',function(){$('[data-parallax="scroll"]').parallax();});}(jQuery,window,document));